// scripts/syncAudioFiles.js - Синхронизация аудио файлов
const fs = require('fs');
const path = require('path');

const AUDIO_DIR = path.join(__dirname, '../assets/audio');
const AUDIO_MAPPING_PATH = path.join(__dirname, '../src/data/audioMapping.ts');

console.log('🚀 Начинаем синхронизацию аудио файлов...');
console.log('==================================================\n');

// Маппинг старых ID категорий на новые названия папок
const CATEGORY_MAPPING = {
  'greetings': 'greetings',
  'emergency': 'emergency',
  'hotel': 'hotel',
  'food': 'food',
  'shopping': 'shopping',
  'transport': 'transport',
  'directions': 'directions',
  'health': 'health',
  'money': 'money',
  'communication': 'communication',
  'entertainment': 'entertainment',
  'time': 'time',
  'numbers': 'numbers',
  'weather': 'weather',
  'personal_info': 'personal_info',
  'business': 'business',
  'measurements': 'measurements',
  'colors': 'colors',
  'body': 'body',
  'home': 'home',
  'customs': 'customs',
  'sport': 'sport'
};

// Сканируем все папки в assets/audio/
console.log('📂 Сканируем аудио файлы...\n');

const audioFiles = {};
let totalFiles = 0;

// Читаем все папки в audio
const folders = fs.readdirSync(AUDIO_DIR).filter(item => {
  return fs.statSync(path.join(AUDIO_DIR, item)).isDirectory();
});

console.log(`Найдено папок: ${folders.length}\n`);

folders.forEach(folder => {
  const folderPath = path.join(AUDIO_DIR, folder);
  const turkmenPath = path.join(folderPath, 'turkmen');
  
  if (fs.existsSync(turkmenPath)) {
    const files = fs.readdirSync(turkmenPath)
      .filter(file => file.endsWith('.mp3'))
      .sort();
    
    if (files.length > 0) {
      console.log(`✅ ${folder}: ${files.length} файлов`);
      
      files.forEach(file => {
        const key = `${folder}/turkmen/${file}`;
        const requirePath = `../../assets/audio/${folder}/turkmen/${file}`;
        audioFiles[key] = requirePath;
        totalFiles++;
      });
    } else {
      console.log(`⚠️  ${folder}: turkmen папка пуста`);
    }
  } else {
    console.log(`⚠️  ${folder}: нет turkmen подпапки`);
  }
});

console.log(`\n📊 Всего найдено: ${totalFiles} MP3 файлов\n`);

// Генерируем audioMapping.ts
console.log('📝 Генерируем audioMapping.ts...');

const audioMappingContent = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/syncAudioFiles.js
// Last updated: ${new Date().toISOString()}

/**
 * Audio file mapping for Turkmen audio files
 * Maps audio keys to require() statements for proper bundling
 */
const TURKMEN_AUDIO: Record<string, any> = {
${Object.entries(audioFiles)
  .map(([key, requirePath]) => `  '${key}': require('${requirePath}'),`)
  .join('\n')}
};

export default TURKMEN_AUDIO;
`;

fs.writeFileSync(AUDIO_MAPPING_PATH, audioMappingContent, 'utf8');
console.log(`✅ Создан audioMapping.ts с ${totalFiles} файлами\n`);

console.log('==================================================');
console.log('✅ СИНХРОНИЗАЦИЯ ЗАВЕРШЕНА УСПЕШНО!\n');
console.log('Следующие шаги:');
console.log('1. Проверьте src/data/audioMapping.ts');
console.log('2. Проверьте что пути правильные');
console.log('3. Запустите: npx expo start');
console.log('4. Протестируйте воспроизведение аудио\n');